# SSO Login configuration
shibboleth_auth_client:
  shibboleth:
    enable_backend_sso: true
    client_auth_endpoint_frontend_route: 'shibboleth_sso_login_frontend'
    client_auth_endpoint_backend_route: 'shibboleth_sso_login_backend'

    # optional frontend user settings
    add_to_frontend_user_groups:
    auto_create_frontend_user: true
    allow_frontend_login_if_contao_account_is_disabled: false
    allowed_frontend_groups:

    # optional backend user settings
    auto_create_backend_user: true
    allow_backend_login_if_contao_account_is_disabled: false
    allowed_backend_groups:
