services:
    _defaults:
        autowire: true
        autoconfigure: true

    iMi\ContaoShibbolethLoginClientBundle\:
        resource: ../src/
        exclude: [
            ../src/{ DependencyInjection,Model,Event,Session,Exception },
            ../src/Client/Provider/SwissAlpineClub.php,
            ../src/Client/OAuth2Client.php,
            ../src/Security/OAuth/OAuthUser.php,
            ../src/Config/ContaoLogConfig.php,
            ../src/ErrorMessage/ErrorMessage.php,
            ../src/Security/User/ContaoUser.php,
        ]

    iMi\ContaoShibbolethLoginClientBundle\Controller\GetLogoutEndpointController:
        public: true
        arguments:
            - '%shibboleth_auth_client.shibboleth.auth_provider_endpoint_logout%'

    iMi\ContaoShibbolethLoginClientBundle\ErrorMessage\ErrorMessageManager:
        arguments:
            - '@request_stack'
            - '%shibboleth_auth_client.session.flash_bag_key%'

    # Register session bags
    markocupic.shibboleth_auth_client.session.factory:
        class: iMi\ContaoShibbolethLoginClientBundle\Session\SessionFactory
        decorates: session.factory
        arguments:
            - '@markocupic.shibboleth_auth_client.session.factory.inner'
            - '@markocupic.shibboleth_auth_client.session.attribute.array_attribute_bag_backend'
            - '@markocupic.shibboleth_auth_client.session.attribute.array_attribute_bag_frontend'

    markocupic.shibboleth_auth_client.session.attribute.array_attribute_bag_backend:
        class: iMi\ContaoShibbolethLoginClientBundle\Session\Attribute\ArrayAttributeBag
        arguments:
            - '_shibboleth_auth_client_attr_backend'
        calls:
            - [ 'setName', [ 'shibboleth_auth_client_attr_backend' ] ]

    markocupic.shibboleth_auth_client.session.attribute.array_attribute_bag_frontend:
        class: iMi\ContaoShibbolethLoginClientBundle\Session\Attribute\ArrayAttributeBag
        arguments:
            - '_shibboleth_auth_client_attr_frontend'
        calls:
            - [ 'setName', [ 'shibboleth_auth_client_attr_frontend' ] ]
