services:

  # Add assets
  iMi\ContaoShibbolethLoginClientBundle\EventSubscriber\KernelRequestSubscriber:
    arguments:
      - '@contao.routing.scope_matcher'
      - '@router'
    tags:
      - { name: kernel.event_subscriber }

  # Handle invalid login attempts
  iMi\ContaoShibbolethLoginClientBundle\EventSubscriber\InvalidLoginAttemptSubscriber:
    arguments:
      - '@contao.framework'
      - '@?logger'
    tags:
      - { name: kernel.event_subscriber }
